### PR TITLE
Fix misnamed model and file

### PR DESCRIPTION
**Pull request by elivz**
I was getting ready to write a similar plugin for a project, so I was very excited to see you release this! It is working great, but I did have to fix two naming issues that were causing errors. The settings model in the main plugin file has the wrong namespace, and the Variable file is plural when it should be singular to match the class name.

### CODE REVIEW

**Review by heymarkreeves — APPROVED** [review]

**Review by heymarkreeves — COMMENTED** [review]
Thanks! I cleaned up the `cmservice` references that were based on copy & paste. Regarding the DarkSkyVariable[s].php filename, I get an errors if I change that filename. It should be the namespace in that file—which is `clearbold\darksky\variables`—combined with the classname—which is `DarkskyVariable`. That's what we see in DarkSky.php: `use clearbold\darksky\variables\DarkskyVariable;`.

**Comment by elivz** [comment]
The variable class is `DarkskyVariable` (singular) though. That's why I had to change the filename to singular to match. I can't explain why it gives you an error one way and me an error the other way ;)

**Comment by heymarkreeves** [comment]
The Campaign Monitor Lists plugin has 451 installs and its folders, filenames, namespaces, and class names are configured the same way. This is the first I've heard of this happening. I'm under the impression that the namespace has to match the folder up to the filename and then the files are parsed for a matching class name. That's not to say naming the file as `DarkskyVariables` is correct :) I'm seeing other plugins with a singular name, too, now that I'm looking closer. But it's possible there was something else afoot. I'll take a closer look at it when I look at some enhancements. And thank you for taking the time to submit the edits! :)

**Comment by heymarkreeves** [comment]
There we go. Now they're all using Variable, singular, in the filename. Took a few `composer update`s. Thanks again!

**Pull request merged**
